import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsNumber } from 'class-validator';

export class CreatePaymentDto {
  @ApiProperty({ description: 'ID of the project associated with this payment' })
  @IsString()
  @IsNotEmpty()
  projectId: string;

  @ApiProperty({ description: 'Payment tier / subscription plan type' })
  @IsString()
  @IsNotEmpty()
  planType: string;

  @ApiProperty({ description: 'Number of borings purchased in this plan' })
  @IsNumber()
  @IsNotEmpty()
  boringsPurchased: number;

  @ApiProperty({ description: 'Total price paid for the borings plan' })
  @IsNumber()
  @IsNotEmpty()
  amountPaid: number;

  @ApiProperty({ description: 'Unique order ID generated by Razorpay' })
  @IsString()
  @IsNotEmpty()
  razorpayOrderId: string;
}
